name: Go package

on: [push]

jobs:
  build_cmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build
        working-directory: ./cmd/example
        run: go build -v ./...
